In [1]:
import pandas as pd
df = pd.read_csv("HDeviceCGM.csv", sep="|")
df.head()

,RecID,ParentHDeviceUploadsID,PtID,SiteID,DeviceDtTmDaysFromEnroll,DeviceTm,DexInternalDtTmDaysFromEnroll,DexInternalTm,RecordType,GlucoseValue
0,1655236,782,183,12,-6,05:35:41,-6.0,12:37:02,CGM,162.0
1,1655237,782,183,12,-6,05:30:41,-6.0,12:32:02,CGM,164.0
2,1655238,782,183,12,-6,05:25:41,-6.0,12:27:02,CGM,168.0
3,1655239,782,183,12,-6,05:20:41,-6.0,12:22:02,CGM,169.0
4,1655240,782,183,12,-6,05:15:41,-6.0,12:17:02,CGM,170.0

In [3]:
df = df[['PtID', 'DeviceDtTmDaysFromEnroll', 'DeviceTm', 'GlucoseValue']]
df.head()

   PtID  DeviceDtTmDaysFromEnroll  DeviceTm  GlucoseValue
0   183                        -6  05:35:41         162.0
1   183                        -6  05:30:41         164.0
2   183                        -6  05:25:41         168.0
3   183                        -6  05:20:41         169.0
4   183                        -6  05:15:41         170.0

In [5]:
df = df.rename(columns={
    'PtID': 'patient_id',
    'DeviceDtTmDaysFromEnroll': 'day',
    'DeviceTm': 'time',
    'GlucoseValue': 'glucose'
})

df.head()

   patient_id  day      time  glucose
0         183   -6  05:35:41    162.0
1         183   -6  05:30:41    164.0
2         183   -6  05:25:41    168.0
3         183   -6  05:20:41    169.0
4         183   -6  05:15:41    170.0

In [7]:
df['timestamp'] = df['day'].astype(str) + ' ' + df['time']
df.head()

   patient_id  day      time  glucose    timestamp
0         183   -6  05:35:41    162.0  -6 05:35:41
1         183   -6  05:30:41    164.0  -6 05:30:41
2         183   -6  05:25:41    168.0  -6 05:25:41
3         183   -6  05:20:41    169.0  -6 05:20:41
4         183   -6  05:15:41    170.0  -6 05:15:41

In [9]:
df = df[['patient_id', 'timestamp', 'glucose']]
df.head()

   patient_id    timestamp  glucose
0         183  -6 05:35:41    162.0
1         183  -6 05:30:41    164.0
2         183  -6 05:25:41    168.0
3         183  -6 05:20:41    169.0
4         183  -6 05:15:41    170.0

In [11]:
df = df.sort_values(['patient_id', 'timestamp'])
df.head()

         patient_id   timestamp  glucose
2958493           2  0 10:37:40    144.0
2958492           2  0 10:38:32    154.0
2958467           2  0 10:41:29    143.0
2958466           2  0 10:46:29    151.0
2958465           2  0 10:51:29    149.0

In [18]:
df['day'] = df['timestamp'].str.split().str[0].astype(int)

df.head()

         patient_id   timestamp  glucose  time_seconds  day
2958493           2  0 10:37:40    144.0       38260.0    0
2958492           2  0 10:38:32    154.0       38312.0    0
2958467           2  0 10:41:29    143.0       38489.0    0
2958466           2  0 10:46:29    151.0       38789.0    0
2958465           2  0 10:51:29    149.0       39089.0    0

In [20]:
df['timestamp_numeric'] = df['day'] * 86400 + df['time_seconds']
df.head()

         patient_id   timestamp  glucose  time_seconds  day  timestamp_numeric
2958493           2  0 10:37:40    144.0       38260.0    0            38260.0
2958492           2  0 10:38:32    154.0       38312.0    0            38312.0
2958467           2  0 10:41:29    143.0       38489.0    0            38489.0
2958466           2  0 10:46:29    151.0       38789.0    0            38789.0
2958465           2  0 10:51:29    149.0       39089.0    0            39089.0

In [22]:
df = df.sort_values(['patient_id', 'timestamp_numeric'])
df.head()

         patient_id   timestamp  glucose  time_seconds  day  timestamp_numeric
2958493           2  0 10:37:40    144.0       38260.0    0            38260.0
2958492           2  0 10:38:32    154.0       38312.0    0            38312.0
2958467           2  0 10:41:29    143.0       38489.0    0            38489.0
2958466           2  0 10:46:29    151.0       38789.0    0            38789.0
2958465           2  0 10:51:29    149.0       39089.0    0            39089.0

In [24]:
df = df[['patient_id', 'timestamp_numeric', 'glucose']]
df.head()

         patient_id  timestamp_numeric  glucose
2958493           2            38260.0    144.0
2958492           2            38312.0    154.0
2958467           2            38489.0    143.0
2958466           2            38789.0    151.0
2958465           2            39089.0    149.0

In [26]:
df.to_csv("C:/Users/Sarah/Downloads/clean_cgm_data.csv", index=False)

In [28]:
df.isna().sum()

patient_id           0
timestamp_numeric    0
glucose              0
dtype: int64

In [30]:
df['glucose'].describe()

count    1.495066e+07
mean     1.603617e+02
std      6.467256e+01
min      2.500000e+01
25%      1.120000e+02
50%      1.500000e+02
75%      1.980000e+02
max      6.000000e+02
Name: glucose, dtype: float64

In [32]:
df = df[df['glucose'] <= 400]

In [36]:
df['glucose'].describe()

count    1.490115e+07
mean     1.595607e+02
std      6.326625e+01
min      2.500000e+01
25%      1.120000e+02
50%      1.500000e+02
75%      1.970000e+02
max      4.000000e+02
Name: glucose, dtype: float64

In [40]:
df.to_csv("C:/Users/Sarah/Downloads/clean_cgm_data_full.csv", index=False)

In [48]:
import numpy as np

np.random.seed(42)

patients = df['patient_id'].unique()
selected_patients = np.random.choice(patients, size=40, replace=False)

df_small = df[df['patient_id'].isin(selected_patients)]

In [50]:
df_small.to_csv("C:/Users/Sarah/Downloads/clean_cgm_data_small.csv", index=False)